### ISSUE TITLE
The Google drive link with corresponding data files do not exist

### ISSUE THREAD

**Issue by tractatus** [Frenzchen/circRNA_paperScripts#1]
Hi @Frenzchen 

Thanks for making all the code for the preprint available here.

I had a specific analysis I wanted to check given your paper. Im particularly interested in checking how the same analysis appears if I would split the dataset into neuronal specific genes versus other circRNAs. Basically is there are subset of neuronal genes that could arise from orthologous exonic loci.

But it looks like the google drive link is dead.

All the best,
Daniel Fürth
CSHL

**Comment by Frenzchen** [comment]
Hello @tractatus,

Thank you for pointing this out. I corrected the link, it should work now.

Best,

Frenzchen

**Comment by tractatus** [comment]
Great! That you for super quick reply and your great work!
